### ISSUE TITLE
JWA: Remove Katib from UI

### ISSUE THREAD

**Issue by rohank07** [StatCan/jupyter-apis#114]
As per our discussion from our tech elab, decided to remove Katib from UI.
![image](https://user-images.githubusercontent.com/28408586/157911617-3da62268-6a97-4f2d-a0de-5096fba121dd.png)

**Comment by rohank07** [comment]
Discussed with Blair and Brendan and a few sticking points were; its not i18nized, may not work and is not widely used amongst users. We are still keeping the manifests on the cluster but removing it from the UI for the time being.

**Comment by brendangadd** [comment]
Feedback I got was that Katib may not actually function presently. So we don't want users who are exploring the platform to click into something broken. Since we know that Katib isn't seeing much or any use yet, it's low impact to remove the menu item. Lack of official languages support is also a contributing factor.

We can leave it accessible users who know the URL so we don't bar them from making use of it. And we can restore the menu link when we've verified that our Katib deployment meets our quality standards. This is a stopgap measure because – due to the little to no usage – addressing Katib issues is not a high priority item.
