### ISSUE TITLE
Visual bug: Custom notebook image does not match type

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#210]
This is a bug that occurs when creating a notebook with a custom image. 

It defaults as a jupyter-notebook.

![image](https://user-images.githubusercontent.com/14837042/223734617-1855211b-8fa8-462a-8f04-7a2901bbf3cf.png)

The fix would be a simple regex or something like that.

**Comment by mathis-marcotte** [comment]
I noticed that issue as well recently. This happens because the icon that gets displayed for the type is determined by what you select here : 
![image](https://user-images.githubusercontent.com/84033116/223741444-7986232c-2ad8-4e29-9ddc-0662b350f5fe.png)

So it's independant of if you check the custom image box to use a custom image or use the default image coming from those 4 types. The reason why it seems like it picks the jupyterlab icon by default is that by default, we pick the jupyterlab image in the form, and I assume that most people that use a custom image don't bother picking the correct image type with those 4 types because it won't matter. 

I agree that a regex can probably be used to determine what the image type is when using a custom image.

**Comment by mathis-marcotte** [comment]
Slightly unrelated but thought about it while working on this ticket.
Thought of moving the "custom image" checkbox to another button with all the image types. it would look a little something like this
![image](https://user-images.githubusercontent.com/84033116/227189956-580f2534-c0c9-4c20-afa2-d0b48d258dcf.png)

This would be because when using a custom image, those image buttons become useless. So at least with a design like this, it would make that group of image types always relevant, while also not increasing the amount of clicks a user would have to make.
The main downside is that with every custom change we make to the code, we get farther away from upstream code which means more complicated version updates
