### ISSUE TITLE
Validation Needed: Able to set Multiple Volume to Same Mount Path

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#215]
There is currently no validation that blocks the user from entering the same mount path for multiple volumes, but two volumes cannot be on the same path, since it will produce an error when trying to start the notebook, even if the notebook was succesfully created through the form. 
One thing to note is that the workspace volume mount path gets set to "/home/jovyan" by default, and that value can't be changed through the frontend like for data volumes. So it might be a good idea to mention that in the frontend since it might not be obvious for users if they try to set a data volume mount path to be "/home/jovyan" while also having a workspace volume.

This validation should also extend to the name component for volumes. For that field, it won't succesfully create the notebook through the form if a user sets the same name for multiple volumes, but the only error returned is from the backend, and we should have the validation in place so that it validates before the user hits "launch" to try and create the notebook(the error message set in the frontend would most likely be more readable than a backend error message).

**Comment by mathis-marcotte** [comment]
Noticed this other potential issue when working on this issue.

The goal for this issue was to add a frontend validation feedback for duplicate mount paths since previously, the error was only caught in the backend by k8s when submitting the notebook. 
But i noticed what looks like a discrepancy in that backend validation. 
You can add a "/" at the end of one of your mount paths so that it results with you having for example one volume with the mount path "/home/jovyan" and then one volume with the mount path "/home/jovyan/". This will pass validation from kubernetes and will mount both to "/home/jovyan".

![image](https://github.com/StatCan/jupyter-apis/assets/84033116/dc32199d-743b-46d5-8038-306192f7b196)

![image](https://github.com/StatCan/jupyter-apis/assets/84033116/e5d9c8d0-a23e-4dd5-8339-3ab21b7c3e2e)
